import Foundation

/// Owns ~/.ssh/config.d/hangar. The file is rewritten wholesale on every sync
/// rather than upserted: terminated instances then disappear on their own, and
/// there is no merge logic to get wrong in a file that can lock the user out of
/// every host they have.
public struct SSHConfigWriter {
    public struct Entry: Sendable {
        public var aliases: [String]
        public var instance: Instance
    }

    public let config: HangarConfig

    public init(config: HangarConfig) {
        self.config = config
    }

    /// Numbers only the aliases that actually collide, oldest instance first, so
    /// a single web box stays `prod-web` while a two-instance ASG becomes
    /// `prod-xfer-1` and `prod-xfer-2`.
    public func entries(for instances: [Instance]) -> [Entry] {
        var groups: [String: [Instance]] = [:]
        for instance in instances where SSHConfigWriter.isWritable(instance) {
            groups[instance.aliasStem, default: []].append(instance)
        }
        var entries: [Entry] = []
        for (stem, members) in groups {
            let ordered = members.sorted { $0.launchTime < $1.launchTime }
            for (index, instance) in ordered.enumerated() {
                let alias = ordered.count > 1 ? "\(stem)-\(index + 1)" : stem
                // Built from the stem, not the numbered alias, so it stays stable
                // when an ASG replaces an instance and the ordinals shuffle. An
                // untagged instance already falls back to its id, and pinning the
                // id to itself would only produce noise.
                var aliases = [alias]
                if stem != Instance.slug(instance.id) {
                    aliases.append("\(stem)-\(instance.id.prefix(10))")
                }
                // Only names that cannot act as a pattern. `Host` is a pattern
                // list, so an unfiltered "*" here would match every host the
                // user has, and Hangar's Include sits above their own config.
                if let host = instance.host, host != alias,
                   SSHConfigValue.isSafeAlias(host) {
                    aliases.append(host)
                }
                var seen = Set<String>()
                entries.append(Entry(
                    aliases: aliases.filter { seen.insert($0).inserted },
                    instance: instance))
            }
        }
        return entries.sorted {
            ($0.instance.product, $0.instance.env, $0.aliases[0])
                < ($1.instance.product, $1.instance.env, $1.aliases[0])
        }
    }

    /// An instance is written only when its hostname can be represented as one
    /// ssh_config argument. A tag carrying a newline could otherwise append a
    /// directive of its own, and ProxyCommand is a directive ssh executes.
    public static func isWritable(_ instance: Instance) -> Bool {
        guard let host = instance.host else { return false }
        return SSHConfigValue.isEmittable(host)
    }

    /// The instances left out of the file, so the caller can say so rather than
    /// have hosts quietly go missing.
    public func omitted(from instances: [Instance]) -> [Instance] {
        instances.filter { $0.host != nil && !SSHConfigWriter.isWritable($0) }
    }

    /// One `  Keyword value` line, quoted if the value needs it, or nothing at
    /// all when the value cannot be represented. Dropping a single option keeps
    /// one bad override from costing the user every alias in the file.
    private func option(_ keyword: String, _ value: String?) -> String? {
        guard let value, SSHConfigValue.isEmittable(value) else { return nil }
        return "  \(keyword) \(SSHConfigValue.quoted(value))"
    }

    public func render(instances: [Instance], region: String, now: Date = Date()) -> String {
        let stamp = ISO8601DateFormatter().string(from: now)
        var lines = [
            "# Generated by Hangar on \(stamp) from \(region). Do not edit;",
            "# every sync rewrites this file, so terminated instances drop out on their own.",
            "# Change ssh user, key, or per-group options in \(HangarConfig.path),",
            "# then sync again from the Hangar menu.",
            "",
        ]
        for entry in entries(for: instances) {
            let instance = entry.instance
            let settings = config.sshSettings(for: instance)
            var meta: [String] = []
            for (key, value) in [("product", instance.product), ("env", instance.env),
                                 ("env_name", instance.envName), ("name", instance.role),
                                 ("asg", instance.asg), ("state", instance.state)]
            where !value.isEmpty {
                meta.append("\(key)=\(SSHConfigValue.comment(value))")
            }
            lines.append("# hangar " + meta.joined(separator: " "))
            // Every alias is checked again here rather than trusted from the
            // caller: this is the one line in the file that is a pattern.
            let names = entry.aliases.filter(SSHConfigValue.isSafeAlias)
            guard !names.isEmpty else { continue }
            lines.append("Host " + names.joined(separator: " "))
            lines.append(contentsOf: [
                option("HostName", instance.host ?? instance.id),
                option("User", settings.user),
            ].compactMap { $0 })
            // Only pin a key when one is configured. Saying nothing lets ssh and
            // the agent behave as they already do, and avoids shutting agent keys
            // out with IdentitiesOnly.
            if let identity = option("IdentityFile", settings.identityFile) {
                lines.append(identity)
                lines.append("  IdentitiesOnly yes")
            }
            lines.append(contentsOf: [
                option("UserKnownHostsFile", settings.knownHostsFile),
                option("StrictHostKeyChecking", settings.strictHostKeyChecking),
            ].compactMap { $0 })
            for (key, value) in (settings.extraOptions ?? [:]).sorted(by: { $0.key < $1.key })
            where SSHConfigValue.isSafeKeyword(key) {
                if let line = option(key, value) { lines.append(line) }
            }
            lines.append("")
        }
        return lines.joined(separator: "\n")
    }

    public struct SyncResult: Sendable {
        public var path: String
        public var hostCount: Int
        /// The line is absent and Hangar did not put it there.
        public var includeLineNeeded: Bool
        /// Hangar added it during this sync.
        public var includeLineAdded: Bool = false
        /// Instance ids left out because their hostname tag could not be written
        /// as a single ssh_config argument.
        public var omittedHosts: [String] = []
    }

    /// Writes to a temporary file, has ssh itself validate the syntax, then moves
    /// it into place. A half-written or malformed file can never take effect.
    @discardableResult
    public func sync(instances: [Instance], region: String,
                     to path: String = HangarConfig.sshIncludePath,
                     ensuringInclude: Bool = false,
                     includePath: String = userConfigPath) throws -> SyncResult {
        let text = render(instances: instances, region: region)
        let fm = FileManager.default
        let directory = (path as NSString).deletingLastPathComponent
        try fm.createDirectory(atPath: directory, withIntermediateDirectories: true,
                               attributes: [.posixPermissions: 0o700])

        let temporary = path + ".\(UUID().uuidString.prefix(8)).tmp"
        try text.write(toFile: temporary, atomically: true, encoding: .utf8)
        try? fm.setAttributes([.posixPermissions: 0o600], ofItemAtPath: temporary)

        if let problem = SSHConfigWriter.validate(temporary) {
            try? fm.removeItem(atPath: temporary)
            throw HangarError.malformedResponse("generated ssh config rejected by ssh: \(problem)")
        }
        _ = try fm.replaceItemAt(URL(fileURLWithPath: path),
                                 withItemAt: URL(fileURLWithPath: temporary))
        // replaceItemAt keeps the destination's own metadata, so a file that was
        // already 0644 would stay 0644 however tight the temporary file was.
        try? fm.setAttributes([.posixPermissions: 0o600], ofItemAtPath: path)

        let count = entries(for: instances).count
        let skipped = omitted(from: instances).map(\.id)
        Log.info(.ssh, "aliases written",
                 ["hosts": "\(count)", "skipped": "\(skipped.count)"])

        // Only after the aliases are in place: an include pointing at a file that
        // failed to write would be a line added for nothing.
        var added = false
        var present = SSHConfigWriter.includeLinePresent(in: includePath)
        if ensuringInclude && !present {
            try SSHConfigWriter.addIncludeLine(to: includePath)
            added = true
            present = true
        }
        return SyncResult(path: path, hostCount: count,
                          includeLineNeeded: !present,
                          includeLineAdded: added,
                          omittedHosts: skipped)
    }

    /// Asks ssh to parse the file. Cheaper and far more accurate than trying to
    /// validate ssh_config syntax ourselves.
    public static func validate(_ path: String) -> String? {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/ssh")
        process.arguments = ["-F", path, "-G", "hangar-syntax-probe"]
        let errors = Pipe()
        process.standardOutput = FileHandle.nullDevice
        process.standardError = errors
        do { try process.run() } catch { return "could not run ssh: \(error)" }
        let data = errors.fileHandleForReading.readDataToEndOfFile()
        process.waitUntilExit()
        guard process.terminationStatus != 0 else { return nil }
        return String(data: data, encoding: .utf8)?
            .trimmingCharacters(in: .whitespacesAndNewlines) ?? "exit \(process.terminationStatus)"
    }

    public static var includeLine: String { "Include ~/.ssh/config.d/hangar" }

    /// The user's own ssh config, which Hangar reads and adds exactly one line to.
    public static var userConfigPath: String {
        NSString(string: "~/.ssh/config").expandingTildeInPath
    }

    public static func includeLinePresent(
        in path: String = NSString(string: "~/.ssh/config").expandingTildeInPath
    ) -> Bool {
        guard let text = try? String(contentsOfFile: path, encoding: .utf8) else { return false }
        return text.components(separatedBy: .newlines).contains { line in
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            return trimmed.hasPrefix("Include") && trimmed.contains("config.d/hangar")
        }
    }

    /// Adds the include as the first line of ~/.ssh/config. It has to sit above
    /// any `Host *` block, because ssh_config is first-match-wins per keyword and
    /// a catch-all above it would beat every entry we generate.
    public static func addIncludeLine(
        to path: String = NSString(string: "~/.ssh/config").expandingTildeInPath
    ) throws {
        guard !includeLinePresent(in: path) else { return }
        let existing = (try? String(contentsOfFile: path, encoding: .utf8)) ?? ""
        let updated = "\(includeLine)\n\n" + existing
        if !existing.isEmpty {
            try? FileManager.default.copyItem(atPath: path, toPath: path + ".hangar-backup")
        }
        try updated.write(toFile: path, atomically: true, encoding: .utf8)
        try? FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: path)
        Log.info(.ssh, "include line added to ~/.ssh/config")
    }

    /// Takes the include back out, for an uninstall. Only lines Hangar would have
    /// written are dropped; the rest of the file is the user's and is preserved.
    /// Returns whether anything was removed.
    @discardableResult
    public static func removeIncludeLine(
        from path: String = NSString(string: "~/.ssh/config").expandingTildeInPath
    ) throws -> Bool {
        guard let existing = try? String(contentsOfFile: path, encoding: .utf8) else { return false }
        var lines = existing.components(separatedBy: .newlines)
        let kept = lines.filter { line in
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            return !(trimmed.hasPrefix("Include") && trimmed.contains("config.d/hangar"))
        }
        guard kept.count != lines.count else { return false }
        lines = kept
        // The line was written with a blank line after it, so removing only the
        // line would leave the file starting on an empty one.
        while lines.first?.trimmingCharacters(in: .whitespaces).isEmpty == true {
            lines.removeFirst()
        }
        try? FileManager.default.removeItem(atPath: path + ".hangar-backup")
        try? FileManager.default.copyItem(atPath: path, toPath: path + ".hangar-backup")
        Log.info(.ssh, "include line removed from ~/.ssh/config")
        try lines.joined(separator: "\n").write(toFile: path, atomically: true, encoding: .utf8)
        // replaceItemAt behind atomically: true keeps its own mode, so set it after.
        try? FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: path)
        return true
    }
}
